{% set name = "zope.deprecation" %}
{% set version = "5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zope_deprecation-{{ version }}.tar.gz
  sha256: 46bed4611fb53edc731aadeb64b28308bcb848f4cc150c60c948d078f7108721

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - zope
    - zope.deprecation

about:
  home: https://github.com/zopefoundation/zope.deprecation
  license: ZPL 2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Zope Deprecation Infrastructure
  doc_url: https://zopedeprecation.readthedocs.io/
  dev_url: https://github.com/zopefoundation/zope.deprecation

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
