{% set name = "zope.deprecation" %}
{% set version = "4.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d453338f04bacf91bbfba545d8bcdf529aa829e67b705eac8c1a7fdce66e2df

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - zope
    - zope.deprecation

about:
  home: https://github.com/zopefoundation/zope.deprecation
  license: ZPL 2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Zope Deprecation Infrastructure
  doc_url: https://zopedeprecation.readthedocs.io/
  dev_url: https://github.com/zopefoundation/zope.deprecation

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
